//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatGame.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChatGame.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to register the following user as a new livestreamer?.
        /// </summary>
        public static string AskRegisterStreamer {
            get {
                return ResourceManager.GetString("AskRegisterStreamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to register the following user as a new livestreamer?.
        /// </summary>
        public static string AskRegisterStreamerAlso {
            get {
                return ResourceManager.GetString("AskRegisterStreamerAlso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to register the following person as a new user?.
        /// </summary>
        public static string AskRegisterUser {
            get {
                return ResourceManager.GetString("AskRegisterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whose chat do you want to log?.
        /// </summary>
        public static string AskWhoToLog {
            get {
                return ResourceManager.GetString("AskWhoToLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choice.
        /// </summary>
        public static string Choice {
            get {
                return ResourceManager.GetString("Choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to Twitch has succeeded..
        /// </summary>
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This console interface is temporary to be able to test the application and will allow some things the final product won&apos;t allow..
        /// </summary>
        public static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user has already been registered as a streamer!.
        /// </summary>
        public static string ExistingStreamer {
            get {
                return ResourceManager.GetString("ExistingStreamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This person has already been registered as a user!.
        /// </summary>
        public static string ExistingUser {
            get {
                return ResourceManager.GetString("ExistingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user has already been registered to be viewing this user!.
        /// </summary>
        public static string ExistingViewer {
            get {
                return ResourceManager.GetString("ExistingViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to Twitch. Do you have a working internet connection?.
        /// </summary>
        public static string FailedTcpClient {
            get {
                return ResourceManager.GetString("FailedTcpClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChatGame.
        /// </summary>
        public static string GameTitle {
            get {
                return ResourceManager.GetString("GameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goodbye!.
        /// </summary>
        public static string Goodbye {
            get {
                return ResourceManager.GetString("Goodbye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds an item of the specified type to the database..
        /// </summary>
        public static string HelpAdd {
            get {
                return ResourceManager.GetString("HelpAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid types:.
        /// </summary>
        public static string HelpAddTypes {
            get {
                return ResourceManager.GetString("HelpAddTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show a list of all available commands..
        /// </summary>
        public static string HelpCommands {
            get {
                return ResourceManager.GetString("HelpCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get to learn more about commands..
        /// </summary>
        public static string HelpHelp {
            get {
                return ResourceManager.GetString("HelpHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a separate console to keep an eye out on someone&apos;s chat..
        /// </summary>
        public static string HelpLogchat {
            get {
                return ResourceManager.GetString("HelpLogchat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &quot;help [command]&quot; to learn more about a command..
        /// </summary>
        public static string HelpMain {
            get {
                return ResourceManager.GetString("HelpMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close this terminal. Won&apos;t close other windows you may have opened!.
        /// </summary>
        public static string HelpQuit {
            get {
                return ResourceManager.GetString("HelpQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a valid command!.
        /// </summary>
        public static string InvalidCommand {
            get {
                return ResourceManager.GetString("InvalidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a valid emoji!.
        /// </summary>
        public static string InvalidEmoji {
            get {
                return ResourceManager.GetString("InvalidEmoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a valid enemy!.
        /// </summary>
        public static string InvalidEnemy {
            get {
                return ResourceManager.GetString("InvalidEnemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That is not a valid response!.
        /// </summary>
        public static string InvalidResponse {
            get {
                return ResourceManager.GetString("InvalidResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a valid streamer!.
        /// </summary>
        public static string InvalidStreamer {
            get {
                return ResourceManager.GetString("InvalidStreamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a valid user!.
        /// </summary>
        public static string InvalidUser {
            get {
                return ResourceManager.GetString("InvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a valid username!.
        /// </summary>
        public static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a valid viewer!.
        /// </summary>
        public static string InvalidViewer {
            get {
                return ResourceManager.GetString("InvalidViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What would you like to do? (type &quot;commands&quot; for a list of commands).
        /// </summary>
        public static string MainMenuText {
            get {
                return ResourceManager.GetString("MainMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The issuer is not an admin.
        /// </summary>
        public static string NonAdminError {
            get {
                return ResourceManager.GetString("NonAdminError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry, but this feature has not been implemented yet. :(.
        /// </summary>
        public static string NotImplementedYet {
            get {
                return ResourceManager.GetString("NotImplementedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;press any key to close this window&gt;.
        /// </summary>
        public static string PressAnyKeyToExit {
            get {
                return ResourceManager.GetString("PressAnyKeyToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for trying out this very early version of.
        /// </summary>
        public static string ThanksForUsing {
            get {
                return ResourceManager.GetString("ThanksForUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer has been started..
        /// </summary>
        public static string TimerStarted {
            get {
                return ResourceManager.GetString("TimerStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer has been stopped..
        /// </summary>
        public static string TimerStopped {
            get {
                return ResourceManager.GetString("TimerStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a known emoji!.
        /// </summary>
        public static string UnkownEmoji {
            get {
                return ResourceManager.GetString("UnkownEmoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is not a registered livestreamer..
        /// </summary>
        public static string UnregisteredStreamer {
            get {
                return ResourceManager.GetString("UnregisteredStreamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This username is not linked to a registered user..
        /// </summary>
        public static string UnregisteredUser {
            get {
                return ResourceManager.GetString("UnregisteredUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is not registered as a viewer of any streamer..
        /// </summary>
        public static string UnregisteredViewer {
            get {
                return ResourceManager.GetString("UnregisteredViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is not registered as a viewer of this streamer..
        /// </summary>
        public static string UnregisteredViewerOfStreamer {
            get {
                return ResourceManager.GetString("UnregisteredViewerOfStreamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.1.4.
        /// </summary>
        public static string VersionId {
            get {
                return ResourceManager.GetString("VersionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (y/n).
        /// </summary>
        public static string YesOrNo {
            get {
                return ResourceManager.GetString("YesOrNo", resourceCulture);
            }
        }
    }
}
